### ISSUE TITLE
给我上owner给我上owner给我上owner

### ISSUE THREAD

**Issue by Wlenk** [contionability/contionability#2]
给我上owner

**Comment by Wlenk** [comment]
给我上owner给我上owner给我上owner给我上owner

**Comment by Wlenk** [comment]
还有discord Dev权限给我一下

**Comment by contionability** [comment]
自导自演是吧

**Comment by contionability** [comment]
nm

**Comment by contionability** [comment]
搞得我连着给几个人道歉

**Comment by contionability** [comment]
dev高考完我再给你
（地铁老人手机

**Comment by Wlenk** [comment]
> dev高考完我再给你 （地铁老人手机

我要update!

**Comment by Wlenk** [comment]
> dev高考完我再给你 （地铁老人手机

discord我现在连话都说不了

**Comment by Wlenk** [comment]
FengXiao开玩笑，封我，给我上了个不知道什么的权限组， 然后他获得了封禁，我也获得了封禁（在Discord中）

**Comment by contionability** [comment]
我说句实话
本来我就要高考了
你这么一搞我压力很大

**Comment by contionability** [comment]
再加上我在学校信息差特别大
（只能访问Github和时不时能访问的Discord）

**Comment by contionability** [comment]
Discord的权限去问Zywl要
我是dev没admin的权限

**Comment by contionability** [comment]
你可以开Pull request来update
高考前我不敢再给别人上权限
怕出事 :(

**Comment by hax0r31337** [comment]
> 再加上我在学校信息差特别大
> （只能访问Github和时不时能访问的Discord）

快高考了就别关心这个破烂圈子了吧，还是专心复习下为好 :)   
祝你能考上心仪的大学

**Comment by Wlenk** [comment]
> 你可以开Pull request来update 高考前我不敢再给别人上权限 怕出事 :(

放心，不可能出事，Pull request我没办法测试能不能下载

**Comment by Wlenk** [comment]
> Discord的权限去问Zywl要 我是dev没admin的权限

他说需要你和他说

**Comment by contionability** [comment]
> > 再加上我在学校信息差特别大
> > （只能访问Github和时不时能访问的Discord）
> 
> 快高考了就别关心这个破烂圈子了吧，还是专心复习下为好 :) 祝你能考上心仪的大学

我成绩还是挺好的
而且这东西本来就是我的兴趣

**Comment by Wlenk** [comment]
owner owner owner
No MemberMemberMemberMemberMemberMember

**Comment by contionability** [comment]
给了你个write权限

**Comment by Wlenk** [comment]
write不够，有的时候nightly.link有的时候会暴毙，导致下载不到文件，需要owner权限去刷新下

**Comment by Wlenk** [comment]
所以i need owner

**Comment by Wlenk** [comment]
![$A9HUYMWFQL0D 2L7%Q X9T](https://user-images.githubusercontent.com/63942405/168458170-b2f3374f-f911-4307-8a7e-b8c9d923a936.png)
不然有可能这样

**Comment by Wlenk** [comment]
![image](https://user-images.githubusercontent.com/63942405/168458175-6dbaf98d-5944-44ba-bf8f-0df3095514da.png)
实际上他是构建成功的

**Comment by contionability** [comment]
https://sm.ms/image/boGZWzM8TeHQfUt
No picture plz

**Comment by hax0r31337** [comment]
> https://sm.ms/image/boGZWzM8TeHQfUt No picture plz

![image](https://getfdp.today/dl/Screenshot_20220516_120309.png)
https://getfdp.today/dl/Screenshot_20220516_120309.png
懒得注册你那个图床了QAQ

**Comment by contionability** [comment]
所有国外网站都寄了except Github
(include .today .club .gg 都寄了)

**Comment by contionability** [comment]
sm.ms只能上传，我看不到我上传的图
就™离谱

**Comment by contionability** [comment]
（或者你可以给我贡献几个HongKong的v2节点）

**Comment by contionability** [comment]
maintain权限有用吗
